Add support for merge keys
dart-lang/yaml pull request #158
Opened 2024-03-16 14:12 UTC by farcaller

Adds support for merge keys and fixes https://github.com/dart-lang/yaml/issues/121.

(this is a copy of the closed #129)

2024-03-16 14:14 UTC, farcaller commented
@mosuem PTAL? The CLA bot says that I have the signature on file since #129 was created.

2024-03-20 09:14 UTC, mosuem commented
Could you copy the description and linked issue into this PR description, add a changelog entry and some tests for this new feature?

2024-06-07 08:54 UTC, jonasfj requested changes

2024-06-07 08:54 UTC, jonasfj commented on lib/src/loader.dart
> +      if (mergeVal is! YamlMap) {
Supposedly the draft says:
```yaml
---
- &CENTER { x: 1, y: 2 }
- &LEFT { x: 0, y: 2 }
- &BIG { r: 10 }
- &SMALL { r: 1 }

# All the following maps are equal:

- # Explicit keys
  x: 1
  y: 2
  r: 10
  label: center/big

- # Merge one map
  << : *CENTER
  r: 10
  label: center/big

- # Merge multiple maps
  << : [ *CENTER, *BIG ]
  label: center/big

- # Override
  << : [ *BIG, *LEFT, *SMALL ]
  x: 1
  label: center/big
```

Last two cases are not handled: https://yaml.org/type/merge.html

2024-06-07 10:42 UTC, jonasfj commented
I propose that this feature should not be implemented in `package:yaml`, see https://github.com/dart-lang/yaml/issues/121#issuecomment-2154574354

2024-12-20 13:36 UTC, mosuem commented
Closing as the [dart-lang/yaml](https://github.com/dart-lang/yaml) repository is merged into the [dart-lang/tools](https://github.com/dart-lang/tools) monorepo. Please re-open this PR there!

2024-12-20 13:36 UTC, closed without merging